//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public System.Guid Id { get; set; }
        public int Seq { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public Nullable<System.DateTime> EmailConfirmedDate { get; set; }
        public bool Enabled { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime LastAccessDate { get; set; }
        public string PictureUrl { get; set; }
        public System.Guid RoleId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
